name: "Test"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create env
        run: | 
          echo export TEST=ABC >> ~/.bash_profile
      - name: echo
        run: |
          env
          source ~/.bash_profile
          env
