name: "Test"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create env
        run: | 
          echo export TEST=ABC >> ~/.bash_profile
          TEST2=ABC
          export TEST3=ABC
      - name: echo
        run: |
          cat ~/.bash_profile
          env
